import = [
  # uncomment the flavour you want below:
  # "~/.config/alacritty/catppuccin-latte.toml"
  # "~/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[font]
size = 12.0

[font.normal]
family = "JetBrains Mono Nerd Font"
style = "Regular"

[window]
opacity = 0.9
padding = { x = 4, y = 0 }
dynamic_padding = true

[selection]
save_to_clipboard = true
